updated

diff --git a/install-jdate b/install-jdate
--- a/install-jdate
+++ b/install-jdate
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-## @last-modified 1400-10-24 21:18:01 +0330 Friday
+## @last-modified 1400-10-29 10:12:28 +0330 Wednesday
 
 ## NOTE this script is used:
 ##      a. for building docker image
@@ -14,7 +14,7 @@ function dl_xtract {
 }
 
 ## needed because user is root when creating docker image, and non-root in GitHub Actions
-(( EUID == 0 )) && is_root='true'
+(( UID > 0 )) || is_root='true'
 
 temp_dir="$(mktemp -d /tmp/jdate_tmp_XXXXXX)"  ## NOTE --,--> Alpine only accepts -d
                                                ##        |--> Alpine requires at least six Xs
@@ -40,14 +40,21 @@ for dep in automake build-essential libjalali-dev libtool; {
 
 printf 'cloning/downloading\n'
 case "$1" in
-  'clone-github' ) git clone https://github.com/ashkang/jcal.git "$temp_dir" ;;
-  'clone-gnu'    ) git clone https://git.savannah.gnu.org/git/jcal.git "$temp_dir" ;;
-  'clone-nongnu' ) git clone https://git.savannah.nongnu.org/git/jcal.git "$temp_dir" ;;
-  'askapache'    ) dl_xtract 'http://nongnu.askapache.com/jcal/jcal-latest.tar.gz' ;;
-  'gnu'          ) dl_xtract 'http://download-mirror.savannah.gnu.org/releases/jcal/jcal-latest.tar.gz' ;;
-  'nongnu'       ) dl_xtract 'http://download.savannah.nongnu.org/releases/jcal/jcal-latest.tar.gz' ;;
-  * ) printf 'invalid source\n'
-      exit 1 ;;
+    'clone-github' )
+        git clone https://github.com/ashkang/jcal.git "$temp_dir" ;;
+    'clone-gnu' )
+        git clone https://git.savannah.gnu.org/git/jcal.git "$temp_dir" ;;
+    'clone-nongnu' )
+        git clone https://git.savannah.nongnu.org/git/jcal.git "$temp_dir" ;;
+    'askapache' )
+        dl_xtract 'http://nongnu.askapache.com/jcal/jcal-latest.tar.gz' ;;
+    'gnu' )
+        dl_xtract 'http://download-mirror.savannah.gnu.org/releases/jcal/jcal-latest.tar.gz' ;;
+    'nongnu' )
+        dl_xtract 'http://download.savannah.nongnu.org/releases/jcal/jcal-latest.tar.gz' ;;
+    * )
+        printf 'invalid source\n'
+        exit 1 ;;
 esac
 
 printf 'installing\n'
diff --git a/movie b/movie
--- a/movie
+++ b/movie
@@ -1,17 +1,12 @@
 #!/usr/bin/env bash
 
-## @last-modified 1400-09-27 21:06:11 +0330 Saturday
+## @last-modified 1400-10-29 10:31:09 +0330 Wednesday
 
 source "$HOME"/scripts/gb
 source "$HOME"/scripts/gb-audacious
 
 function no_such_file {
     msgc 'ERROR' "no such file as <span color=\"${orange}\">\$HOME/movie/${directory}/${movie}</span>" "$HOME"/linux/themes/alert-w.png
-    exit
-}
-
-function no_such_dir {
-    msgc 'ERROR' "no such directory as <span color=\"${orange}\">\$HOME/movie/${directory}/${movie}</span>" "$HOME"/linux/themes/alert-w.png
     exit
 }
 
@@ -33,6 +28,30 @@ function success_removing {
 
 function error_removing {
     msgc 'ERROR' "removing <span color=\"${orange}\">${base}</span>" "$HOME"/linux/themes/alert-w.png
+}
+
+function if_empty {  ## JUMP_1 the same used in "$HOME"/scripts/speech
+    local count
+
+    read count directory <<< "$directory"  ## 8 pargar
+
+    ## check if count is an int
+    [ "$count" -eq "$count" ] || {
+        msgc 'ERROR' "<span color=\"${orange}\">${count}</span> is invalid count" "$HOME"/linux/themes/alert-w.png
+        exit
+    }
+
+    (( count > 0 )) || {
+        msgn 'nothing here'
+        exit
+    }
+}
+
+function if_dir {  ## JUMP_1
+    [ -d "$HOME"/movie/"$directory" ] || {
+        msgc 'ERROR' "no such directory as <span color=\"${orange}\">\$HOME/movie/${directory}</span>" "$HOME"/linux/themes/alert-w.png
+        exit
+    }
 }
 
 declare -a directories_plus_count
@@ -60,18 +79,18 @@ for tmp_directory in "${directories[@]}"; {
 }
 
 directory="$(pipe_to_rofi "${directories_plus_count[@]}" "header=${title}")" || exit 37
-
-directory="${directory##*' '}"  ## remove count
-
-## pick
-[ -d "$HOME"/movie/"$directory" ] || no_such_dir
+if_empty  ## NOTE if_empty must precede if_dir
+if_dir
 
 case "$1" in
-    random ) movie="$(shuf -n 1 < <(find "$HOME"/movie/"$directory" -mindepth 1 -maxdepth 1 -type f ! -iname '*.srt'))"
-             movie="${movie##*/}" ;;
-    select ) readarray -t movies < <(find "$HOME"/movie/"$directory" -mindepth 1 -maxdepth 1 -type f ! -iname '*.srt' | sort)
-             movie="$(pipe_to_rofi "${movies[@]##*/}" "header=${directory}")" || exit 37 ;;
-    * ) exit ;;  ## NOTE do NOT remove
+    random )
+        movie="$(shuf -n 1 < <(find "$HOME"/movie/"$directory" -mindepth 1 -maxdepth 1 -type f ! -iname '*.srt'))"
+        movie="${movie##*/}" ;;
+    select )
+        readarray -t movies < <(find "$HOME"/movie/"$directory" -mindepth 1 -maxdepth 1 -type f ! -iname '*.srt' | sort)
+        movie="$(pipe_to_rofi "${movies[@]##*/}" "header=${directory}")" || exit 37 ;;
+    * )
+        exit ;;  ## NOTE do NOT remove
 esac
 
 ## play
@@ -82,15 +101,17 @@ vlc -f --play-and-exit -- "$HOME"/movie/"$directory"/"$movie" 2>/dev/null
 
 ## move to WATCHED or remove
 what_to_dos=( '' 'mv to WATCHED' 'remove' )
-what_to_do="$(pipe_to_rofi "${what_to_dos[@]}" "header=${movie}" 'bg=red')" # || exit 37  ## the exit is exceptionally commented
+what_to_do="$(pipe_to_rofi "${what_to_dos[@]}" "header=${movie}" 'bg=red')"  # || exit 37  ## the exit is exceptionally commented
 
 case "$what_to_do" in
-    'mv to WATCHED' ) [ -d "$HOME"/movie/"$directory"/WATCHED ] || mkdir "$HOME"/movie/"$directory"/WATCHED
-                      mv "$HOME"/movie/"$directory"/"$movie" "$HOME"/movie/"$directory"/WATCHED && success_moving || error_moving ;;
-
-    remove ) rm "$HOME"/movie/"$directory"/"$movie" && success_removing || error_removing ;;
-    # * ) : ;;  ## NOTE do NOT uncomment
+    'mv to WATCHED' )
+        [ -d "$HOME"/movie/"$directory"/WATCHED ] || mkdir "$HOME"/movie/"$directory"/WATCHED
+        mv "$HOME"/movie/"$directory"/"$movie" "$HOME"/movie/"$directory"/WATCHED && success_moving || error_moving ;;
+    remove )
+        rm "$HOME"/movie/"$directory"/"$movie" && success_removing || error_removing ;;
+    # * )  ## NOTE keep commented
+    #     exit ;;
 esac
 
-## play audacious if it was playing before the video
+## play audacious if it was playing before the video was played
 [ "$continue_playing" == 'true' ] && "$HOME"/scripts/awesome-widgets audacious play_pause
diff --git a/speech b/speech
--- a/speech
+++ b/speech
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-## @last-modified 1400-10-01 08:21:16 +0330 Wednesday
+## @last-modified 1400-10-29 11:01:31 +0330 Wednesday
 
 source "$HOME"/scripts/gb
 source "$HOME"/scripts/gb-audacious
@@ -9,9 +9,28 @@ function update_audacious {
     "$HOME"/scripts/awesome-widgets audacious
 }
 
-function no_such_dir {
-    msgc 'ERROR' "no such directory as <span color=\"${orange}\">\$HOME/speech/${directory}</span>" "$HOME"/linux/themes/alert-w.png
-    exit
+function if_empty {  ## JUMP_2 the same used in "$HOME"/scripts/movie
+    local count
+
+    read count directory <<< "$directory"  ## 8 pargar
+
+    ## check if count is an int
+    [ "$count" -eq "$count" ] || {
+        msgc 'ERROR' "<span color=\"${orange}\">${count}</span> is invalid count" "$HOME"/linux/themes/alert-w.png
+        exit
+    }
+
+    (( count > 0 )) || {
+        msgn 'nothing here'
+        exit
+    }
+}
+
+function if_dir {  ## JUMP_2
+    [ -d "$HOME"/speech/"$directory" ] || {
+        msgc 'ERROR' "no such directory as <span color=\"${orange}\">\$HOME/speech/${directory}</span>" "$HOME"/linux/themes/alert-w.png
+        exit
+    }
 }
 
 function success_moving {
@@ -48,84 +67,81 @@ for tmp_directory in "${directories[@]}"; {
 }
 
 case "$1" in
-    play ) directory="$(pipe_to_rofi "${directories_plus_count[@]}" 'header=speech')" || exit 37
+    play )
+        directory="$(pipe_to_rofi "${directories_plus_count[@]}" 'header=speech')" || exit 37  ## '8 pargar'
 
-           directory="${directory##*' '}"  ## remove count
+        if_empty  ## NOTE JUMP_1 if_empty must precede if_dir
+        if_dir
 
-           [ -d "$HOME"/speech/"$directory" ] || no_such_dir
+        turn_off_shuffle; sleep 0.1
+        clear_playlist  ; sleep 0.1
 
-           turn_off_shuffle; sleep 0.1
-           clear_playlist  ; sleep 0.1
+        msgn 'playing' "<span color=\"${orange}\">${directory}</span>" "$HOME"/linux/themes/user-w.png
 
-           msgn 'playing' "<span color=\"${orange}\">${directory}</span>" "$HOME"/linux/themes/user-w.png
+        readarray -t first_five_files < <(find "$HOME"/speech/"$directory" -mindepth 1 -maxdepth 1 -iname '*.mp3' | sort | head -n 5)
+        audacious -E "${first_five_files[@]}"  # &
+        sleep 0.1
+        "$HOME"/scripts/awesome-widgets audacious resume ;;
+    move )
+        if [ "$2" == 'auto' ]; then
+            ## NOTE the auto option is called directly by audacious when starting a new song
 
-           readarray -t first_five_files < <(find "$HOME"/speech/"$directory" -mindepth 1 -maxdepth 1 -iname '*.mp3' | sort | head -n 5)
-           audacious -E "${first_five_files[@]}"  # &
-           sleep 0.1
-           "$HOME"/scripts/awesome-widgets audacious resume ;;
+            [ "$album" == 'speech' ] || exit  ## NOTE do NOT combine with the parent condition
 
-    move ) ## exit if album is not speech
-           [ "$album" == 'speech' ] || exit  ## NOTE <--,-- do NOT remove this line because audacious is told to run the scripts with remove auto args
-                                             ##         '-- whenever starting a new song no matter what the album is
+            directory="${current_song_dir##*/}"  ## pargar
+        else
+            directory="$(pipe_to_rofi "${directories_plus_count[@]}" 'header=speech' 'bg=red')" || exit 37
+            if_empty  ## NOTE JUMP_1 if_empty must precede if_dir
+        fi
 
-           if [ "$2" == 'auto' ]; then
-              ## this option is called directly by audacious when starting a new song
+        if_dir
 
-              directory="${current_song_dir}"  ## /home/nnnn/speech/pargar
-              directory="${directory##*/}"  ## pargar
-           else
-               directory="$(pipe_to_rofi "${directories_plus_count[@]}" 'header=speech' 'bg=red')" || exit 37
-               ## remove count:
-               directory="${directory##*' '}"  ## pargar
-           fi
+        first_file="$(find "$HOME"/speech/"$directory" -mindepth 1 -maxdepth 1 -iname '*.mp3' | sort | head -n 1)"  ## /home/nnnn/speech/pargar/709.mp3
 
-           [ -d "$HOME"/speech/"$directory" ] || no_such_dir
+        base="${first_file##*/}"
+        no_suffix="${base%.*}"
 
-           first_file="$(find "$HOME"/speech/"$directory" -mindepth 1 -maxdepth 1 -iname '*.mp3' | sort | head -n 1)"  ## /home/nnnn/speech/pargar/709.mp3
+        ## exit if first file is the same as the current song
+        [ "$current_song" == "$first_file" ] && exit
 
-           base="${first_file##*/}"
-           no_suffix="${base%.*}"
+        [ -d "$HOME"/speech/"$directory"/LISTENED ] || mkdir "$HOME"/speech/"$directory"/LISTENED
+        mv "$first_file" "$HOME"/speech/"$directory"/LISTENED && success_moving || error_moving
 
-           ## exit if first file is the same as the current song
-           [ "$current_song" == "$first_file" ] && exit
+        ## trigger add_4 only if current playing file is the last file in playlist
+        if (( playlist_length == position_in_playlist )); then
+            "$HOME"/scripts/speech add_4
+        else
+            update_audacious
+        fi ;;
+    add_4 )
+        if [ ! "$album" ] || [ "$album" == 'speech' ]; then
 
-           [ -d "$HOME"/speech/"$directory"/LISTENED ] || mkdir "$HOME"/speech/"$directory"/LISTENED
-           mv "$first_file" "$HOME"/speech/"$directory"/LISTENED && success_moving || error_moving
-
-           ## trigger add_4 only if current playing file is the last file in playlist
-           if (( playlist_length == position_in_playlist )); then
-               "$HOME"/scripts/speech add_4
-           else
-               update_audacious
-           fi ;;
-    add_4 ) if [ ! "$album" ] || [ "$album" == 'speech' ]; then
-
-                ## remove previous files from playlist
-                if (( position_in_playlist == 1 )); then
-                    :
-                elif (( position_in_playlist > 1 )); then
-                    for ((i=1; i<"$position_in_playlist"; i++)); {
-                        audtool --playlist-delete 1
-                        sleep 0.01
-                    }
-                elif [ ! "$position_in_playlist" ]; then
-                    clear_playlist
-                    "$HOME"/scripts/speech play &
-                    exit
-                fi
-
-                ## add 4 new files to playlist
-                readarray -t first_five_files < <(find "$current_song_dir" -mindepth 1 -maxdepth 1 -iname '*.mp3' | sort | head -n 5)
-                current_songs="$(audtool --playlist-display)"
-
-                for file in "${first_five_files[@]}"; {
-                    base="${file##*/}"
-                    no_suffix="${base%.*}"
-                    if ! \grep -qi "$no_suffix" <<< "$current_songs"; then
-                        audacious -e "$file"
-                        msgn "added <span color=\"${orange}\">${no_suffix}</span>"
-                    fi
+            ## remove previous files from playlist
+            if (( position_in_playlist == 1 )); then
+                :
+            elif (( position_in_playlist > 1 )); then
+                for ((i=1; i<"$position_in_playlist"; i++)); {
+                    audtool --playlist-delete 1
+                    sleep 0.01
                 }
-                update_audacious
-            fi ;;
+            elif [ ! "$position_in_playlist" ]; then
+                clear_playlist
+                "$HOME"/scripts/speech play &
+                exit
+            fi
+
+            ## add 4 new files to playlist
+            readarray -t first_five_files < <(find "$current_song_dir" -mindepth 1 -maxdepth 1 -iname '*.mp3' | sort | head -n 5)
+            current_songs="$(audtool --playlist-display)"
+
+            for file in "${first_five_files[@]}"; {
+                base="${file##*/}"
+                no_suffix="${base%.*}"
+                if ! \grep -qi "$no_suffix" <<< "$current_songs"; then
+                    audacious -e "$file"
+                    msgn "added <span color=\"${orange}\">${no_suffix}</span>"
+                fi
+            }
+            update_audacious
+        fi ;;
 esac
