updated

diff --git a/install-jcal b/install-jcal
--- a/install-jcal
+++ b/install-jcal
@@ -1,13 +1,8 @@
 #!/usr/bin/env bash
 
-## @last-modified 1400-10-12 16:54:52 +0330 Sunday
+## @last-modified 1400-10-12 17:21:16 +0330 Sunday
 
 ## NOTE this file is used a. for making docker image, and b. in action-jcal
-
-## needed because user is root when creating docker image, and non-root in GitHub Actions
-(( EUID == 0 )) && is_root='true'
-
-temp_dir="$(mktemp --directory)"
 
 function dl_xtract {
     mkdir -p "$temp_dir"/sources
@@ -15,8 +10,13 @@ function dl_xtract {
     tar -xf "$temp_dir"/jcal_latest.tar.gz -C "$temp_dir"/sources
 }
 
+## needed because user is root when creating docker image, and non-root in GitHub Actions
+(( EUID == 0 )) && is_root='true'
+
+temp_dir="$(mktemp --directory)"
+
 printf 'installing dependencies\n'
-for dep in automake build-essential libjalali-dev libtool git; {
+for dep in automake build-essential libjalali-dev libtool; {
     [ "$(which "$dep")" ] && continue
     if [ "$is_root" == 'true' ]; then
         apt install -y --no-install-recommends "$dep"
@@ -31,7 +31,7 @@ case "$1" in
   'clone-gnu' ) git clone https://git.savannah.gnu.org/git/jcal.git "$temp_dir" ;;
   'gnu' ) dl_xtract 'http://download-mirror.savannah.gnu.org/releases/jcal/jcal-latest.tar.gz' ;;
   'askapache' ) dl_xtract 'http://nongnu.askapache.com/jcal/jcal-latest.tar.gz' ;;
-  * ) printf 'wrong source\n'; exit 1 ;;
+  * ) printf 'invalid source\n'; exit 1 ;;
 esac
 
 printf 'installing\n'
